//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// このソース コードは xsd によって自動生成されました。Version=4.6.1055.0 です。
// 
namespace EarphoneLeftAndRight.Schemas.AuthorInformation {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/WordbookImpressApp/blob/master/WordbookImpressApp/Wordb" +
        "ookImpressLibrary/Schemas/AuthorInformation.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://github.com/kurema/WordbookImpressApp/blob/master/WordbookImpressApp/Wordb" +
        "ookImpressLibrary/Schemas/AuthorInformation.xsd", IsNullable=false)]
    public partial class author {
        
        private string nameField;
        
        private authorLink[] linksField;
        
        private authorGroup[] donationsField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("link", IsNullable=false)]
        public authorLink[] links {
            get {
                return this.linksField;
            }
            set {
                this.linksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("group", IsNullable=false)]
        public authorGroup[] donations {
            get {
                return this.donationsField;
            }
            set {
                this.donationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/WordbookImpressApp/blob/master/WordbookImpressApp/Wordb" +
        "ookImpressLibrary/Schemas/AuthorInformation.xsd")]
    public partial class authorLink {
        
        private authorLinkTitle titleField;
        
        private string srcField;
        
        private string title1Field;
        
        /// <remarks/>
        public authorLinkTitle title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string src {
            get {
                return this.srcField;
            }
            set {
                this.srcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("title")]
        public string title1 {
            get {
                return this.title1Field;
            }
            set {
                this.title1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/WordbookImpressApp/blob/master/WordbookImpressApp/Wordb" +
        "ookImpressLibrary/Schemas/AuthorInformation.xsd")]
    public partial class authorLinkTitle {
        
        private multilingalEntry[] multilingalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable=false)]
        public multilingalEntry[] multilingal {
            get {
                return this.multilingalField;
            }
            set {
                this.multilingalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/WordbookImpressApp/blob/master/WordbookImpressApp/Wordb" +
        "ookImpressLibrary/Schemas/AuthorInformation.xsd")]
    public partial class multilingalEntry {
        
        private string languageField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="language")]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/WordbookImpressApp/blob/master/WordbookImpressApp/Wordb" +
        "ookImpressLibrary/Schemas/AuthorInformation.xsd")]
    public partial class authorGroup {
        
        private authorGroupTitle titleField;
        
        private authorGroupDonation[] donationField;
        
        private string title1Field;
        
        /// <remarks/>
        public authorGroupTitle title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("donation")]
        public authorGroupDonation[] donation {
            get {
                return this.donationField;
            }
            set {
                this.donationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("title")]
        public string title1 {
            get {
                return this.title1Field;
            }
            set {
                this.title1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/WordbookImpressApp/blob/master/WordbookImpressApp/Wordb" +
        "ookImpressLibrary/Schemas/AuthorInformation.xsd")]
    public partial class authorGroupTitle {
        
        private multilingalEntry[] multilingalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable=false)]
        public multilingalEntry[] multilingal {
            get {
                return this.multilingalField;
            }
            set {
                this.multilingalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/WordbookImpressApp/blob/master/WordbookImpressApp/Wordb" +
        "ookImpressLibrary/Schemas/AuthorInformation.xsd")]
    public partial class authorGroupDonation {
        
        private authorGroupDonationTitle titleField;
        
        private string addressField;
        
        private string srcField;
        
        private string title1Field;
        
        /// <remarks/>
        public authorGroupDonationTitle title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string src {
            get {
                return this.srcField;
            }
            set {
                this.srcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("title")]
        public string title1 {
            get {
                return this.title1Field;
            }
            set {
                this.title1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/WordbookImpressApp/blob/master/WordbookImpressApp/Wordb" +
        "ookImpressLibrary/Schemas/AuthorInformation.xsd")]
    public partial class authorGroupDonationTitle {
        
        private multilingalEntry[] multilingalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable=false)]
        public multilingalEntry[] multilingal {
            get {
                return this.multilingalField;
            }
            set {
                this.multilingalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/WordbookImpressApp/blob/master/WordbookImpressApp/Wordb" +
        "ookImpressLibrary/Schemas/AuthorInformation.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://github.com/kurema/WordbookImpressApp/blob/master/WordbookImpressApp/Wordb" +
        "ookImpressLibrary/Schemas/AuthorInformation.xsd", IsNullable=false)]
    public partial class multilingal {
        
        private multilingalEntry[] entryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entry")]
        public multilingalEntry[] entry {
            get {
                return this.entryField;
            }
            set {
                this.entryField = value;
            }
        }
    }
}
