//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EarphoneLeftAndRight.Resx {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EarphoneLeftAndRight.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Webster&apos;s Dictionary, 1913 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dict_Dict_Title {
            get {
                return ResourceManager.GetString("Dict.Dict.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dictionary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dict_Header {
            get {
                return ResourceManager.GetString("Dict.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;Left&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;b&gt;Left&lt;/b&gt;&lt;br/&gt;
        ///(lĕft), &lt;I&gt;imp. &amp;amp; p. p.&lt;/I&gt;of ≪Leave≫.&lt;br/&gt;
        ///&lt;hr/&gt;
        ///&lt;b&gt;Left&lt;/b&gt;&lt;br/&gt;
        ///&lt;I&gt;a.&lt;/I&gt;[OE. &lt;I&gt;left&lt;/I&gt;, &lt;I&gt;lift&lt;/I&gt;, &lt;I&gt;luft&lt;/I&gt;; akin to Fries. &lt;I&gt;leeft&lt;/I&gt;, OD. &lt;I&gt;lucht&lt;/I&gt;, &lt;I&gt;luft&lt;/I&gt;; cf. AS. &lt;I&gt;left&lt;/I&gt; (equiv. to L. &lt;I&gt;inanis&lt;/I&gt;), &lt;I&gt;lyftādl&lt;/I&gt; palsy; or cf. AS. &lt;I&gt;lēf&lt;/I&gt; weak.] Of or pertaining to that side of the body in man on which the muscular action of the limbs is usually weaker than on the other side; -- [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dict_Left_Html {
            get {
                return ResourceManager.GetString("Dict.Left.Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dict_Left_Title {
            get {
                return ResourceManager.GetString("Dict.Left.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;Right&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;b&gt;Right&lt;/b&gt;&lt;br/&gt;
        ///(rīt), &lt;I&gt;a.&lt;/I&gt;[OE. &lt;I&gt;right&lt;/I&gt;, &lt;I&gt;riht&lt;/I&gt;, AS. &lt;I&gt;riht&lt;/I&gt;; akin to D. &lt;I&gt;regt&lt;/I&gt;, OS. &amp;amp; OHG. &lt;I&gt;reht&lt;/I&gt;, G. &lt;I&gt;recht&lt;/I&gt;, Dan. &lt;I&gt;ret&lt;/I&gt;, Sw. rätt, Icel. &lt;I&gt;rëttr&lt;/I&gt;, Goth. &lt;I&gt;raí	hts&lt;/I&gt;, L. &lt;I&gt;rectus&lt;/I&gt;, p. p. of &lt;I&gt;regere&lt;/I&gt; to guide, rule; cf. Skr. &lt;I&gt;ṛju&lt;/I&gt; straight, right. ✓115. Cf. ≪Adroit≫,≪Alert≫, ≪Correct≫, ≪Dress≫, ≪Regular≫, ≪Rector≫, ≪Recto≫, ≪Rectum≫, ≪Regent≫, ≪Region≫, ≪Realm≫, ≪Rich≫, [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dict_Right_Html {
            get {
                return ResourceManager.GetString("Dict.Right.Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Dict_Right_Title {
            get {
                return ResourceManager.GetString("Dict.Right.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detail に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_DetailPage {
            get {
                return ResourceManager.GetString("License.DetailPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_Open {
            get {
                return ResourceManager.GetString("License.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   License に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string License_Title {
            get {
                return ResourceManager.GetString("License.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you left or right? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string More_OpenCompass_Title {
            get {
                return ResourceManager.GetString("More.OpenCompass.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://politicalcompass.org/test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string More_OpenCompass_URL {
            get {
                return ResourceManager.GetString("More.OpenCompass.URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   What is &quot;left&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string More_OpenDictionary_Left {
            get {
                return ResourceManager.GetString("More.OpenDictionary.Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   What is &quot;right&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string More_OpenDictionary_Right {
            get {
                return ResourceManager.GetString("More.OpenDictionary.Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   More about Left/Right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string More_Title {
            get {
                return ResourceManager.GetString("More.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Play_Title {
            get {
                return ResourceManager.GetString("Play.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   kurema に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Profile_Accounts_Github_ID {
            get {
                return ResourceManager.GetString("Profile.Accounts.Github.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Profile_Bio {
            get {
                return ResourceManager.GetString("Profile.Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contact に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Profile_Contact {
            get {
                return ResourceManager.GetString("Profile.Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Donation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Profile_Donation_Header {
            get {
                return ResourceManager.GetString("Profile.Donation.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Profile_Email_Header {
            get {
                return ResourceManager.GetString("Profile.Email.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Followers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Profile_Followers_Header {
            get {
                return ResourceManager.GetString("Profile.Followers.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GitHub Sponsors に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Profile_GitHubSponsors {
            get {
                return ResourceManager.GetString("Profile.GitHubSponsors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Projects に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Profile_Projects_Header {
            get {
                return ResourceManager.GetString("Profile.Projects.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Profile_Support_Button {
            get {
                return ResourceManager.GetString("Profile.Support.Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Support Us に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Profile_Support_Title {
            get {
                return ResourceManager.GetString("Profile.Support.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Profile_Title {
            get {
                return ResourceManager.GetString("Profile.Title", resourceCulture);
            }
        }
    }
}
