name: CI on Push and Pull Request
on: [push, pull_request]
jobs:
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
# For Windows    
#    - name: Add msbuild to PATH
#      uses: microsoft/setup-msbuild@v1.0.3
    - name: Android
      run: |
        cd Earphone
        nuget restore
        msbuild EarphoneLeftAndRight/EarphoneLeftAndRight.Android/EarphoneLeftAndRight.Android.csproj /verbosity:normal /t:Rebuild /t:PackageForAndroid /t:SignAndroidPackage /p:Configuration=Release 
    - uses: actions/upload-artifact@v2
      with:
        name: Android App
        path: Earphone/EarphoneLeftAndRight/EarphoneLeftAndRight.Android/bin/Release/com.github.kurema.earphoneleftandright-Signed.apk
