name: CI on Push and Pull Request
on: [push, pull_request]
jobs:
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
# For Windows    
#    - name: Add msbuild to PATH
#      uses: microsoft/setup-msbuild@v1.0.3
    - name: write keystore
      run: |
        echo $KEYSTORE_BASE64 | base64 --decode > Earphone/github.keystore
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64_ENCODED }}
    - name: Android
      run: |
        cd Earphone
        nuget restore
        msbuild EarphoneLeftAndRight/EarphoneLeftAndRight.Android/EarphoneLeftAndRight.Android.csproj /verbosity:normal /t:Rebuild /t:PackageForAndroid /t:SignAndroidPackage /p:Configuration=Release /p:AndroidKeyStore=True /p:AndroidSigningKeyStore=github.keystore /p:AndroidSigningStorePass=${{ secrets.KEYSTORE_PASSWORD }} /p:AndroidSigningKeyAlias=github /p:AndroidSigningKeyPass=${{ secrets.KEYSTORE_PASSWORD }}
    - name: delete keystore
      run: |
        rm github.keystore
    - uses: actions/upload-artifact@v2
      with:
        name: Android App
        path: Earphone/EarphoneLeftAndRight/EarphoneLeftAndRight.Android/bin/Release/com.github.kurema.earphoneleftandright-Signed.aab
